workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      node: 16.x
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npm install -g @ionic/cli
          
      - name: Build web app
        script: |
          npm run build
          
      - name: Set up Capacitor
        script: |
          npm install @capacitor/cli @capacitor/core
          npx cap add android
          npx cap sync
          
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - email@exemplo.com # Substitua pelo seu email
        notify:
          success: true
          failure: true
