workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
      node: latest
      xcode: latest
      java: 11
      groups:
        - keystore_credentials
      
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true

    scripts:
      - name: Install dependencies
        script: |
          npm install -g @ionic/cli
          npm install --legacy-peer-deps
          
      - name: Build web app
        script: |
          ionic build --prod
          
      - name: Add Android platform
        script: |
          ionic cap add android
          
      - name: Update Android platform
        script: |
          ionic cap sync android
          
      - name: Build Android release
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - email@exemplo.com # Substitua pelo seu email
        notify:
          success: true
          failure: true
