workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      node: latest
      java: 11.0
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.filemanager.app"
      
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true

    scripts:
      - name: Install dependencies
        script: |
          npm install -g @ionic/cli
          npm install --legacy-peer-deps
          
      - name: Build web app
        script: |
          ionic build --prod
          
      - name: Set up Android
        script: |
          ionic cap add android
          ionic cap sync android
          
      - name: Build Android
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - email@exemplo.com # Substitua pelo seu email
        notify:
          success: true
          failure: true
